<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <RootNamespace>PhantomQoL</RootNamespace>
        <AssemblyName>PhantomQoL</AssemblyName>
        <OutputType>Library</OutputType>
        <LangVersion>latest</LangVersion>
        <OutputPath>..\..\build\plugins\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <TerrariaPath>F:\Apps\Steam\steamapps\common\Terraria</TerrariaPath>
        <ModId>$([System.Text.RegularExpressions.Regex]::Match($([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)\manifest.json')), '"id":\s*"([^"]+)"').Groups[1].Value)</ModId>
        <ModInstallPath>$(TerrariaPath)\TerrariaModder\mods\$(ModId)</ModInstallPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Terraria">
            <HintPath>$(TerrariaPath)\Terraria.exe</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="TerrariaModder.Core">
            <HintPath>$(TerrariaPath)\TerrariaModder\core\TerrariaModder.Core.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>$(TerrariaPath)\TerrariaModder\core\deps\0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Microsoft.Xna.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553">
            <HintPath>C:\Windows\Microsoft.NET\assembly\GAC_32\Microsoft.Xna.Framework\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Microsoft.Xna.Framework.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553">
            <HintPath>C:\Windows\Microsoft.NET\assembly\GAC_32\Microsoft.Xna.Framework.Graphics\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Graphics.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Microsoft.Xna.Framework.Game, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553">
            <HintPath>C:\Windows\Microsoft.NET\assembly\GAC_32\Microsoft.Xna.Framework.Game\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Game.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <Target Name="DeployToModFolder" AfterTargets="Build">
        <MakeDir Directories="$(ModInstallPath)"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModInstallPath)"/>
        <Copy SourceFiles="$(MSBuildProjectDirectory)\manifest.json" DestinationFolder="$(ModInstallPath)"/>
    </Target>
</Project>